apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: doc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doc
  template:
    metadata:
      labels:
        app: doc
    spec:
      containers:
      - name: doc
        image: sathishsiddamsetty/doc:latest
        ports:
        - containerPort: 80
